# Generated by Django 3.0.3 on 2020-07-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevotionalVerse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=900, unique=True)),
                ('BCV', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerseOfTheDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse', models.CharField(max_length=900, unique=True)),
                ('BCV', models.CharField(max_length=264, unique=True)),
                ('date', models.CharField(max_length=264, unique=True)),
            ],
        ),
    ]
