# Generated by Django 2.1.3 on 2020-07-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchApp', '0002_sermon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
