# Generated by Django 2.1.3 on 2020-07-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchApp', '0003_auto_20200712_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.CharField(max_length=900, unique=True)),
            ],
        ),
    ]
